export default {
  'likes': '{likes, number} me gusta',
  'logout': 'Salir',
  'english': 'Ingles',
  'spanish': 'Español',
  'signup-subheading': 'Regístrate para ver fotos de tus amigos',
  'signup-facebook': 'Iniciar sesión con Facebook',
  'signup-face': 'Iniciar sesión',
  'email': 'Correo Electronico',
  'username': 'Nombre de usuario',
  'fullname': 'Nombre completo',
  'password': 'Contraseña',
  'signup': 'Registrate',
  'signup.have-account': '¿Tienes una cuenta?',
  'signin': 'Entrar',
  'signin.have-account': '¿No tienes una cuenta?',
  'language': 'Idioma',
  'upload-picture': 'Subir imagen',
  'upload': 'Subir'
}
